#!/bin/bash

. hooks/config

#set -e
while [ -e Temp/UnityLockFile ]
do
	echo I cannot build while the project is still open in Unity. I will wait 5 seconds and try again.
	sleep 5
done

echo "running tests"
set -e
"$MSBuildLocation" tests/KusoTest/KusoTest.sln
"$MSTestLocation" /testcontainer:tests/KusoTest/KusoTest/bin/Debug/KusoTest.dll

echo "executing build"
"$unityLocation" -batchmode -quit -projectpath $projectFolder -buildOSXUniversalPlayer $workingFolder/mac/$projectName/$projectName.app

hooks/butler push $workingFolder/mac/$projectName $itchURL:mac$1
echo "pushed!"